#!/bin/bash

# This script launches all processes needed by 3 postures instances to run together.

function start_remote_term {    
    # Runs a remote command in a terminal using SSH
    # arg1 = user@hostname
    # arg2 = command to run
    echo rxvt -e ssh $1 "${2}" 
    rxvt -e ssh $1 "${2}" &
}

function start_local_term {    
    # Runs a command in a terminal
    # arg1 = command to run
    echo rxvt -e $1
    rxvt -e $1 &
}
function start_remote_term_with_x {    
    # Runs a remote command in a terminal using SSH
    # arg1 = user@hostname
    # arg2 = command to run
    echo rxvt -e ssh -X $1 "${2}" 
    rxvt -e ssh -X $1 "${2}" &
}
# ----------------------- NTA specific stuff -----------------
NTA=~/src/nta
POSTURES=~/src/postures/trunk
SPINWIDGETS=~/src/spinwidgets
SPIN=~/src/spinframework/trunk
# Variables, not aliases. -------------------
# We assume the correct .pdsettings have been installed from our svn repository.
# We assume the LD_LIBRARY_PATH is correctly set.
# Use custom pd instead of installed version:
pd="~/src/pd-0.41-4/bin/pd -jack"
spinEdit="pd ${SPINWIDGETS}/patches/spinEdit.pd"
spinViewer="${SPIN}/src/vess/spinViewer"
panoViewer="${POSTURES}/panoViewer/panoViewer"
ntaClient="pd ${NTA}/ntaClient.pd"

# ------------------------- just a test ---------------
USERHOST="aalex@tzing"
COMMAND="mplayer /usr/share/example-content/Experience\ ubuntu.ogg"
# start_remote_term "${USERHOST}" "${COMMAND}"

# -------------------------- serious launcher ---------

start_local_term "vessServer"
sleep 5
start_local_term "${panoViewer}"
start_local_term "${ntaClient}"
start_remote_term "postures@postures02" "${panoViewer}"
start_remote_term "postures@postures02" "${ntaClient}"
start_remote_term "postures@postures03" "${panoViewer}"
start_remote_term "postures@postures03" "${ntaClient}"

