#!/bin/bash

# This script launches all processes needed by 3 postures instances to run together.
# should be started from the computer #2. (postures02)
# remotely launches #1 and #3.

function start_remote_term {    
    # Runs a remote command in a terminal using SSH
    # arg1 = user@hostname
    # arg2 = command to run
    #echo rxvt -e ssh $1 "${2}" \&
    rxvt -T "${2##*=* }" -e ssh $1 $2 &
}

function start_local_term {    
    # Runs a command in a terminal
    # arg1 = command to run
    #echo rxvt -e $1
    rxvt -e "$1" &
}

# ----------------------- NTA specific stuff -----------------
NTA=~/src/nta
POSTURES=~/src/postures/trunk
SPINWIDGETS=~/src/spinwidgets
SPIN=~/src/spinframework/trunk

# Variables, not aliases. -------------------
# We assume the correct .pdsettings have been installed from our svn repository.
# We assume the LD_LIBRARY_PATH is correctly set.
# Use custom pd instead of installed version:
pd="~/src/pd-0.41-4/bin/pd -jack"
spinEdit="pd ${SPINWIDGETS}/patches/spinEdit.pd"
spinViewer="${SPIN}/src/vess/spinViewer"
panoViewer="${POSTURES}/panoViewer/panoViewer"
ntaClient="pd ${NTA}/ntaClient.pd"
vessServer="${SPIN}/src/vess/vessServer"

# ------------------------- just a test ---------------
# uncomment there 3 lines for a simple test.
# USERHOST="aalex@tzing"
# COMMAND="mplayer /usr/share/example-content/Experience\ ubuntu.ogg"
# start_remote_term "${USERHOST}" "${COMMAND}"

# -------------------------- serious launcher ---------
start_local_term "${vessServer}"
sleep 3
start_local_term "LD_LIBRARY_PATH=${SPIN}/src/osgWrappers ${panoViewer}"
start_local_term "${ntaClient}"
for user_host in postures@10.20.10.1{1,3};
do
    start_remote_term "${user_host}" "killall panoViewer pd"
    start_remote_term "${user_host}" "DISPLAY=:0.0 LD_LIBRARY_PATH=${SPIN}/src/osgWrappers ${panoViewer}"
    start_remote_term "${user_host}" "DISPLAY=:0.0 ${ntaClient}"
done

