#!/bin/bash

# This script launches all processes needed by 3 postures instances to run together.
# should be started from the computer #2. (postures02)
# remotely launches #1 and #3.

function start_remote_term {    
    # Runs a remote command in a terminal using SSH
    # arg1 = user@hostname
    # arg2 = command to run
    echo rxvt -e ssh $1 "${2}" \&
    rxvt -e ssh $1 "${2}" &
}

function start_local_term {    
    # Runs a command in a terminal
    # arg1 = command to run
    echo rxvt -e $1
    rxvt -e $1 &
}

function start_remote_term_with_x {    
    # Runs a remote command in a terminal using SSH
    # arg1 = user@hostname
    # arg2 = command to run
    echo rxvt -e ssh -X $1 "${2}" 
    rxvt -e ssh -X $1 "${2}" &
}

# ----------------------- NTA specific stuff -----------------
NTA=~/src/nta
POSTURES=~/src/postures/trunk
SPINWIDGETS=~/src/spinwidgets
SPIN=~/src/spinframework/trunk

# Variables, not aliases. -------------------
# We assume the correct .pdsettings have been installed from our svn repository.
# We assume the LD_LIBRARY_PATH is correctly set.
# Use custom pd instead of installed version:
pd="~/src/pd-0.41-4/bin/pd -jack"
spinEdit="pd ${SPINWIDGETS}/patches/spinEdit.pd"
spinViewer="${SPIN}/src/vess/spinViewer"
panoViewer="${POSTURES}/panoViewer/panoViewer"
ntaClient="pd ${NTA}/ntaClient.pd"

# ------------------------- just a test ---------------
# uncomment there 3 lines for a simple test.
# USERHOST="aalex@tzing"
# COMMAND="mplayer /usr/share/example-content/Experience\ ubuntu.ogg"
# start_remote_term "${USERHOST}" "${COMMAND}"

# -------------------------- serious launcher ---------
start_local_term "vessServer"
sleep 5
start_local_term "${panoViewer}"
start_local_term "${ntaClient}"
for i in {1,3};
do
    start_remote_term "postures@10.20.10.1${i}" "export DISPLAY=:0.0\\;sleep 1\\;export LD_LIBRARY_PATH=${SPIN}/src/osgWrappers\\;${panoViewer}\\;sleep 1\\;"
    start_remote_term "postures@10.20.10.1${i}" "export DISPLAY=:0.0\\;sleep 1\\;${ntaClient}\\;sleep 1\\;"
done

