# This make file installs the launch_postures custom script and a Gnome 
# application in the Applications/Other menu.
#
all:
	@echo DONE
install:
	install Postures.desktop /usr/local/share/applications/Postures.desktop
	install launch_postures /usr/local/bin/launch_postures

